### PR TITLE
connected to API and added pseudo code😎

### PR DESCRIPTION
**Pull request by Edjrich**
Please review the code friends

or else...

### CODE REVIEW

**Review by michellelven — APPROVED** [review]
Awesome-sauce! We have connected to the API successfully! Pseudo-code too! 👍

**Comment by AHeroOfTime** [comment]
Looks sketchy to me...

**Review by michellelven — APPROVED** [review]
AWESOMESAUCE AGAIN!

**Review by AHeroOfTime — APPROVED** [review]
Looks sketchy...but ok

**Review by NicoleBrady — APPROVED** [review]
looks good

**Pull request merged**
