### PR TITLE
added logic for conditional rendereing of Form component when game is…

### PR DESCRIPTION
**Pull request by AHeroOfTime**
… over. Added state for rounds to be tracked with counter.

### CODE REVIEW

**Comment by AHeroOfTime** [comment]
🥉 I concur ----v

**Review by Edjrich — APPROVED** [review]
game logic 🎮 🤔 

🎮 🔫 🥴

**Review by NicoleBrady — APPROVED** [review]
much wow

**Review by michellelven — APPROVED** [review]
This is exciting. Can't wait to take a closer look today. Good Job! ❤️

**Pull request merged**
